collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2616487
  brandStrength: 0
  lightness: 0.2777778
  brandColors:
    - '#FFFFFF'
    - '#271F20'
    - '#FF6F64'
    - '#6F6D6E'
    - '#BD656E'
  rhythmicContrast: 0.6756272
typography_spectrum: 0.281362
layout_spectrum: 0.8602151
name: Mafyoo
